const expressions = [
  // Greetings
  {
    id: 1,
    expression: "How's it going?",
    translation: "¿Cómo va todo?",
    meaning: "Saludo informal para preguntar cómo está alguien.",
    example: "Hey John! How's it going? — Pretty well, thanks!",
    exampleTranslation: "¡Hola John! ¿Cómo va todo? — Bastante bien, ¡gracias!",
    category: "greetings",
    level: "beginner",
  },
  {
    id: 2,
    expression: "Long time no see!",
    translation: "¡Cuánto tiempo sin verte!",
    meaning: "Se usa cuando no has visto a alguien en mucho tiempo.",
    example: "Long time no see! How have you been?",
    exampleTranslation: "¡Cuánto tiempo sin verte! ¿Cómo has estado?",
    category: "greetings",
    level: "beginner",
  },
  {
    id: 3,
    expression: "What's up?",
    translation: "¿Qué hay? / ¿Qué pasa?",
    meaning: "Saludo muy informal, equivalente a '¿Qué tal?'.",
    example: "What's up, guys? Ready for the game?",
    exampleTranslation: "¿Qué hay, chicos? ¿Listos para el partido?",
    category: "greetings",
    level: "beginner",
  },
  {
    id: 4,
    expression: "Take care!",
    translation: "¡Cuídate!",
    meaning: "Despedida informal para desearle bien a alguien.",
    example: "It was great seeing you. Take care!",
    exampleTranslation: "Fue genial verte. ¡Cuídate!",
    category: "greetings",
    level: "beginner",
  },

  // Business
  {
    id: 5,
    expression: "Touch base",
    translation: "Ponerse en contacto / Hacer seguimiento",
    meaning: "Contactar a alguien brevemente para actualizar o revisar algo.",
    example: "Let's touch base next week to see how the project is going.",
    exampleTranslation: "Pongámonos en contacto la próxima semana para ver cómo va el proyecto.",
    category: "business",
    level: "intermediate",
  },
  {
    id: 6,
    expression: "Think outside the box",
    translation: "Pensar fuera de lo convencional",
    meaning: "Ser creativo y pensar de manera no convencional.",
    example: "We need to think outside the box to solve this problem.",
    exampleTranslation: "Necesitamos pensar de forma creativa para resolver este problema.",
    category: "business",
    level: "intermediate",
  },
  {
    id: 7,
    expression: "Get the ball rolling",
    translation: "Poner las cosas en marcha",
    meaning: "Iniciar un proceso o actividad.",
    example: "Let's get the ball rolling on the new marketing campaign.",
    exampleTranslation: "Pongamos en marcha la nueva campaña de marketing.",
    category: "business",
    level: "intermediate",
  },
  {
    id: 8,
    expression: "On the same page",
    translation: "De acuerdo / En la misma sintonía",
    meaning: "Estar de acuerdo o tener el mismo entendimiento sobre algo.",
    example: "Before we start, let's make sure we're all on the same page.",
    exampleTranslation: "Antes de empezar, asegurémonos de estar todos de acuerdo.",
    category: "business",
    level: "intermediate",
  },
  {
    id: 9,
    expression: "Bottom line",
    translation: "En resumen / Lo más importante",
    meaning: "El punto más importante o el resultado final.",
    example: "The bottom line is that we need to increase sales by 20%.",
    exampleTranslation: "En resumen, necesitamos aumentar las ventas en un 20%.",
    category: "business",
    level: "intermediate",
  },
  {
    id: 10,
    expression: "Hit the ground running",
    translation: "Empezar con todo",
    meaning: "Comenzar algo con energía y preparación total desde el principio.",
    example: "She hit the ground running on her first day at the new job.",
    exampleTranslation: "Ella empezó con todo desde su primer día en el nuevo trabajo.",
    category: "business",
    level: "advanced",
  },

  // Emotions
  {
    id: 11,
    expression: "On top of the world",
    translation: "Feliz como nunca / En la cima",
    meaning: "Sentirse extremadamente feliz o exitoso.",
    example: "After getting the promotion, she felt on top of the world.",
    exampleTranslation: "Después del ascenso, se sentía en la cima del mundo.",
    category: "emotions",
    level: "beginner",
  },
  {
    id: 12,
    expression: "Down in the dumps",
    translation: "Deprimido / Triste",
    meaning: "Sentirse triste o deprimido.",
    example: "He's been down in the dumps since his team lost the championship.",
    exampleTranslation: "Ha estado muy deprimido desde que su equipo perdió el campeonato.",
    category: "emotions",
    level: "intermediate",
  },
  {
    id: 13,
    expression: "Butterflies in your stomach",
    translation: "Mariposas en el estómago / Nervioso",
    meaning: "Sentir nerviosismo o emoción, especialmente antes de algo importante.",
    example: "I always get butterflies in my stomach before a job interview.",
    exampleTranslation: "Siempre siento nerviosismo antes de una entrevista de trabajo.",
    category: "emotions",
    level: "beginner",
  },
  {
    id: 14,
    expression: "Blow off steam",
    translation: "Desahogarse / Liberar tensión",
    meaning: "Hacer algo para liberar estrés o frustración acumulada.",
    example: "I like to go for a run to blow off steam after work.",
    exampleTranslation: "Me gusta salir a correr para desahogarme después del trabajo.",
    category: "emotions",
    level: "intermediate",
  },

  // Idioms
  {
    id: 15,
    expression: "Break the ice",
    translation: "Romper el hielo",
    meaning: "Hacer o decir algo para aliviar la tensión en una situación social.",
    example: "He told a joke to break the ice at the meeting.",
    exampleTranslation: "Contó un chiste para romper el hielo en la reunión.",
    category: "idioms",
    level: "beginner",
  },
  {
    id: 16,
    expression: "Bite the bullet",
    translation: "Aguantar / Morder el polvo",
    meaning: "Soportar una situación dolorosa o difícil con valentía.",
    example: "I had to bite the bullet and tell him the bad news.",
    exampleTranslation: "Tuve que armarte de valor y darle las malas noticias.",
    category: "idioms",
    level: "intermediate",
  },
  {
    id: 17,
    expression: "Hit the nail on the head",
    translation: "Dar en el clavo",
    meaning: "Describir exactamente cuál es el problema o decir algo muy acertado.",
    example: "You hit the nail on the head — that's exactly the issue.",
    exampleTranslation: "Diste en el clavo, ese es exactamente el problema.",
    category: "idioms",
    level: "intermediate",
  },
  {
    id: 18,
    expression: "Spill the beans",
    translation: "Revelar un secreto",
    meaning: "Contar un secreto o revelar información confidencial.",
    example: "Who spilled the beans about the surprise party?",
    exampleTranslation: "¿Quién reveló el secreto sobre la fiesta sorpresa?",
    category: "idioms",
    level: "beginner",
  },
  {
    id: 19,
    expression: "Under the weather",
    translation: "Sentirse mal / Indispuesto",
    meaning: "Sentirse enfermo o mal de salud.",
    example: "I'm feeling a bit under the weather today, so I'll stay home.",
    exampleTranslation: "Hoy no me siento muy bien, así que me quedaré en casa.",
    category: "idioms",
    level: "beginner",
  },
  {
    id: 20,
    expression: "Beat around the bush",
    translation: "Andarse por las ramas",
    meaning: "Evitar ir directo al punto o hablar de manera indirecta.",
    example: "Stop beating around the bush and tell me what happened!",
    exampleTranslation: "¡Deja de andarte por las ramas y dime qué pasó!",
    category: "idioms",
    level: "intermediate",
  },
  {
    id: 21,
    expression: "Once in a blue moon",
    translation: "De vez en cuando / Muy raramente",
    meaning: "Algo que ocurre muy pocas veces.",
    example: "We only go out for dinner once in a blue moon.",
    exampleTranslation: "Solo salimos a cenar fuera muy de vez en cuando.",
    category: "idioms",
    level: "beginner",
  },
  {
    id: 22,
    expression: "Bite off more than you can chew",
    translation: "Abarcar más de lo que se puede",
    meaning: "Intentar hacer algo que está más allá de tus capacidades.",
    example: "I bit off more than I could chew by taking three courses at once.",
    exampleTranslation: "Me sobreexigí al tomar tres cursos al mismo tiempo.",
    category: "idioms",
    level: "advanced",
  },

  // Social
  {
    id: 23,
    expression: "Hang out",
    translation: "Pasar el rato / Juntarse",
    meaning: "Pasar tiempo con amigos de manera relajada.",
    example: "Do you want to hang out this weekend?",
    exampleTranslation: "¿Quieres que quedemos este fin de semana?",
    category: "social",
    level: "beginner",
  },
  {
    id: 24,
    expression: "Give someone a hand",
    translation: "Echar una mano / Ayudar",
    meaning: "Ayudar a alguien con algo.",
    example: "Can you give me a hand with these boxes?",
    exampleTranslation: "¿Me puedes echar una mano con estas cajas?",
    category: "social",
    level: "beginner",
  },
  {
    id: 25,
    expression: "Go the extra mile",
    translation: "Hacer un esfuerzo extra",
    meaning: "Esforzarse más de lo necesario para conseguir algo.",
    example: "She always goes the extra mile for her students.",
    exampleTranslation: "Siempre hace un esfuerzo extra por sus estudiantes.",
    category: "social",
    level: "intermediate",
  },
  {
    id: 26,
    expression: "In the same boat",
    translation: "En la misma situación",
    meaning: "Estar en la misma situación difícil que otra persona.",
    example: "We're all in the same boat — nobody knows what will happen next.",
    exampleTranslation: "Todos estamos en la misma situación, nadie sabe qué pasará.",
    category: "social",
    level: "intermediate",
  },
  {
    id: 27,
    expression: "Break a leg!",
    translation: "¡Mucha suerte! / ¡Mucho éxito!",
    meaning: "Expresión para desear buena suerte, especialmente en actuaciones.",
    example: "You've got the big audition today — break a leg!",
    exampleTranslation: "Hoy tienes la gran audición. ¡Mucha suerte!",
    category: "social",
    level: "beginner",
  },

  // Time
  {
    id: 28,
    expression: "In the nick of time",
    translation: "Justo a tiempo",
    meaning: "Llegar o hacer algo exactamente cuando se necesitaba.",
    example: "We caught the train in the nick of time.",
    exampleTranslation: "Cogimos el tren justo a tiempo.",
    category: "time",
    level: "intermediate",
  },
  {
    id: 29,
    expression: "Around the clock",
    translation: "Las 24 horas / Sin parar",
    meaning: "Durante todo el día, sin interrupciones.",
    example: "The rescue team worked around the clock to find survivors.",
    exampleTranslation: "El equipo de rescate trabajó las 24 horas para encontrar supervivientes.",
    category: "time",
    level: "intermediate",
  },
  {
    id: 30,
    expression: "At the last minute",
    translation: "A última hora",
    meaning: "Hacer algo muy tarde, casi cuando ya es demasiado tarde.",
    example: "He always finishes his homework at the last minute.",
    exampleTranslation: "Siempre termina sus deberes a última hora.",
    category: "time",
    level: "beginner",
  },
  {
    id: 31,
    expression: "Take your time",
    translation: "Tómate tu tiempo",
    meaning: "No hay prisa, haz las cosas con calma.",
    example: "Take your time — we're not in a hurry.",
    exampleTranslation: "Tómate tu tiempo, no tenemos prisa.",
    category: "time",
    level: "beginner",
  },
  {
    id: 32,
    expression: "Time flies",
    translation: "El tiempo vuela",
    meaning: "El tiempo pasa muy rápidamente.",
    example: "Time flies when you're having fun!",
    exampleTranslation: "¡El tiempo vuela cuando te estás divirtiendo!",
    category: "time",
    level: "beginner",
  },
];
